[CI] Enable automatic NOLINT check (#373)
Forbid `NOLINT*` comments usage

diff --git a/.github/workflows/static-analysis-pr.yml b/.github/workflows/static-analysis-pr.yml
--- a/.github/workflows/static-analysis-pr.yml
+++ b/.github/workflows/static-analysis-pr.yml
@@ -78,3 +78,22 @@ jobs:
         run: |
           echo "clang-tidy run has failed. See previous 'Run clang-tidy' stage logs"
           exit 1
+  nolint-check:
+    runs-on: ubuntu-24.04
+    steps:
+      - uses: actions/checkout@v4
+      - name: Search for NOLINT
+        run: |
+          export BASE_REF=${{ github.event.pull_request.base.ref }}
+          export CHANGED_FILES="$(git diff --name-only origin/$BASE_REF HEAD | grep '^tasks/')"
+          if [ -z "$CHANGED_FILES" ]; then
+            echo "No changed files in tasks directory."
+            exit 0
+          fi
+          for file in $CHANGED_FILES; do
+            if grep -n "NOLINT" "$file"; then
+              echo "::error::Found 'NOLINT' in $file."
+              exit 1
+            fi
+          done
+          echo "No 'NOLINT' markers found in changed files."
